os:
  - linux
  - osx
script:
  - bash bin/bootstrap.sh
  - source $HOME/.bash_profile
  - conda create --name "py27-travis-test" --clone "py27-base"
  - conda create --name "py35-travis-test" --clone "py35-base"
  - source activate py27-travis-test
  - conda install --yes scikit-bio
  - source deactivate
  - source activate py35-travis-test
  - conda install --yes scikit-bio
  - source deactivate
